#!/usr/bin/env python
"""Generate digitizer_core/threads_isacord.py from the repo's Isacord chart.

Source: ../tools/palettes/"InkStitch Isacord Polyester.gpl" — thread color
numbers and RGB approximations are factual data (owner ruling 2026-07-29:
facts-doctrine applies in both products; Isacord/Amann is a pure thread
manufacturer, allowed under the no-software-company-brands policy).

Run from digitizer/:  .venv/Scripts/python tools/gen_isacord.py
Deterministic output: entries sorted by catalog number, LF line endings,
so the generated file is byte-identical regardless of source line endings.
"""
from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
GPL = HERE.parent.parent / "tools" / "palettes" / "InkStitch Isacord Polyester.gpl"
OUT = HERE.parent / "digitizer_core" / "threads_isacord.py"

LINE = re.compile(r"^(\d{1,3})\s+(\d{1,3})\s+(\d{1,3})\s+(.+)$")


def parse(text: str) -> list[tuple[str, str, tuple[int, int, int]]]:
    entries = []
    for raw in re.split(r"\r\n|\r|\n", text):
        line = raw.strip()
        if not line or line.startswith("#") or line.lower().startswith(("gimp palette", "name:", "columns:")):
            continue
        m = LINE.match(line)
        if not m:
            continue
        r, g, b = int(m.group(1)), int(m.group(2)), int(m.group(3))
        if max(r, g, b) > 255:
            continue
        rest = m.group(4).strip()
        # last whitespace-separated token containing a digit = catalog number
        parts = rest.rsplit(None, 1)
        if len(parts) == 2 and any(c.isdigit() for c in parts[1]):
            name, number = parts[0].strip(), parts[1].strip()
        else:
            name, number = rest, ""
        if name:
            entries.append((number, name, (r, g, b)))
    return entries


def main() -> None:
    entries = parse(GPL.read_text(encoding="utf-8"))
    if len(entries) < 350:
        raise SystemExit(f"parsed only {len(entries)} entries from {GPL} — format change?")
    entries.sort(key=lambda e: e[0])
    lines = [
        '"""GENERATED by tools/gen_isacord.py — do not edit by hand.',
        "",
        "Isacord Polyester 40 thread chart (catalog number, name, approximate RGB).",
        "Factual manufacturer color-chart data; Isacord is a trademark of the",
        "Amann Group, used only to identify the thread line.",
        '"""',
        "",
        "ISACORD = [",
    ]
    for number, name, rgb in entries:
        lines.append(f"    ({number!r}, {name!r}, {rgb!r}),")
    lines.append("]")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(entries)} threads)")


if __name__ == "__main__":
    main()
