// Credits data derived from the font manifest — never hand-maintained.
//
// Per-font license obligations (font-license-audit-2026-07-31.md items 6+7):
// - attribution: the complete user-visible notice (adapter credit + upstream
//   copyright + Reserved-Font-Name declarations), generated by
//   tools/font-license.mjs at build/patch time.
// - licenseHref: the font's FULL license text, shipped as a stand-alone file
//   at /fonts/<key>.LICENSE.txt (copied by app/scripts/copy-engine.mjs) —
//   the OFL's "stand-alone text files" delivery option; a local copy also
//   satisfies CC-BY/CC-BY-SA's "text of, or URI to, this license" uniformly.
// - modificationNote: CC-BY-SA 4.0 §3(a)(1)(B) requires indicating that the
//   work was modified; stated for every font since it's true of all of them
//   (vector font -> quantized stitch-path .embf compile).
export const MODIFICATION_NOTE =
  "Modified from the original: adapted for machine embroidery (satin stitch paths) " +
  "and compiled to EMB-Bot's .embf binary format (coordinates quantized).";

export function creditLines(manifestFonts) {
  return (manifestFonts || [])
    .map((f) => ({
      name: f.name || f.key,
      licenseId: f.licenseId || "",
      attribution: f.attribution || "",
      source: f.source || "",
      binHref: "/fonts/bin/" + f.key + ".embf",
      licenseHref: "/fonts/" + f.key + ".LICENSE.txt",
      modificationNote: MODIFICATION_NOTE,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}
