"""Split the suite across CI shards, deterministically, by test FILE.

Inert unless ``DIGITIZER_SHARD=<k>/<n>`` is set (1-based k). A local
``python -m pytest`` never sets it and runs everything, exactly as before.

WHY FILES, NOT TESTS. 67 fixtures here are module-scoped and some are whole
pipeline runs. Splitting one file across shards would recompute those in every
shard that drew a piece of it, so the shards would do more total work than the
single job did. A file is the unit that keeps that work done once.

HOW. Longest-processing-time first: files sorted by their recorded duration
(``.shard_durations.json``, regenerated by ``tools/ci_shard_durations.py``),
each given to the currently lightest shard. A file with no recorded duration
gets the median, so a new test file lands somewhere sane without a refresh.
Every shard computes the SAME assignment from the same collected list, so the
shards are disjoint and together cover every collected test. The aggregator
job named ``digitizer`` checks that from the manifests written below rather
than taking it on trust.
"""

import json
import os
from pathlib import Path

import pytest

DURATIONS = Path(__file__).with_name(".shard_durations.json")


def _parse(spec):
    k, n = (int(x) for x in spec.split("/"))
    if not 1 <= k <= n:
        raise ValueError(f"DIGITIZER_SHARD={spec!r}: need 1 <= k <= n")
    return k, n


def assign(files, n, durations):
    """Map each file to a shard index 0..n-1. Pure, so it is testable."""
    known = sorted(v for f, v in durations.items() if f in files)
    default = known[len(known) // 2] if known else 1.0
    weight = {f: durations.get(f, default) for f in files}
    loads = [0.0] * n
    out = {}
    # Ties broken by name, so the order never depends on set iteration.
    for f in sorted(files, key=lambda f: (-weight[f], f)):
        i = min(range(n), key=lambda i: (loads[i], i))
        out[f] = i
        loads[i] += weight[f]
    return out


# trylast: run after the CLI's --deselect, so the manifest's ``collected`` is
# the set CI actually runs -- the three golden deselects already gone.
@pytest.hookimpl(trylast=True)
def pytest_collection_modifyitems(config, items):
    spec = os.environ.get("DIGITIZER_SHARD")
    if not spec:
        return
    k, n = _parse(spec)
    manifest = os.environ.get("DIGITIZER_SHARD_MANIFEST")
    # Consumed here, so no CHILD process inherits them. tests/test_doc_claims.py
    # runs its own `pytest --collect-only`; with these still set, that child
    # collected only this shard's files (quietly narrowing its count check)
    # and, lacking the CLI's --deselects, overwrote this shard's manifest
    # with 3 extra ids -- the aggregator's first red, PR #669.
    os.environ.pop("DIGITIZER_SHARD", None)
    os.environ.pop("DIGITIZER_SHARD_MANIFEST", None)
    # "wire" when CI ran only tools/ci_wire_tests.py's subset (a PR that
    # touched neither digitizer/ nor .github/); the aggregator checks it.
    scope = os.environ.pop("DIGITIZER_SCOPE", "full")
    durations = json.loads(DURATIONS.read_text()) if DURATIONS.exists() else {}
    files = {item.nodeid.split("::", 1)[0] for item in items}
    shard_of = assign(files, n, durations)
    full = [item.nodeid for item in items]
    keep = [it for it in items if shard_of[it.nodeid.split("::", 1)[0]] == k - 1]
    drop = [it for it in items if shard_of[it.nodeid.split("::", 1)[0]] != k - 1]
    items[:] = keep
    config.hook.pytest_deselected(items=drop)

    # Under xdist every worker collects; one manifest is enough (gw0, or the
    # lone process without -n).
    worker = getattr(config, "workerinput", {}).get("workerid")
    if manifest and worker in (None, "gw0"):
        Path(manifest).write_text(json.dumps(
            {"shard": k, "of": n, "scope": scope, "collected": full,
             "selected": [it.nodeid for it in keep]}))
