#!/usr/bin/env node
// build-threads.mjs — converts the GIMP-palette (.gpl) thread charts in
// tools/palettes/ into app/src/lib/threadBrands.js, the static brand catalog
// the Studio's ThreadPicker + Download thread summary consume.
//
// Provenance: the .gpl files are manufacturer color charts redistributed by
// the Ink/Stitch project (github.com/inkstitch/inkstitch, palettes/). Thread
// color numbers and their RGB approximations are factual data (a catalog of
// facts, not creative expression); each brand name remains a trademark of its
// manufacturer and is used only to identify the corresponding thread line.
//
// Usage: node tools/build-threads.mjs
// Re-run whenever a palette file in tools/palettes/ is added or updated.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const PALETTE_DIR = join(root, "tools", "palettes");
const OUT = join(root, "app", "src", "lib", "threadBrands.js");

// Which .gpl files ship, and the short ids/labels the UI shows for them.
// Order here is the order brands appear in the picker dropdown.
const BRANDS = [
  { file: "InkStitch Isacord Polyester.gpl", id: "isacord", label: "Isacord Polyester 40" },
  { file: "InkStitch Madeira Polyneon.gpl", id: "polyneon", label: "Madeira Polyneon 40" },
  { file: "InkStitch Madeira Rayon.gpl", id: "madeira-rayon", label: "Madeira Rayon 40" },
  { file: "InkStitch Robison-Anton Polyester.gpl", id: "robison-anton", label: "Robison-Anton Polyester 40" },
];

// A .gpl body line is "R G B <name words> <catalog number>", whitespace
// (spaces and/or tabs) separated, after a 3-4 line header. The catalog number
// is the last field; it always contains a digit in these charts, which is how
// we tell it apart from a name-only line (some palettes ship without codes --
// then the whole remainder is the name and code is "").
function parseGpl(text) {
  const entries = [];
  for (const raw of text.split(/\r\n|\r|\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#") || /^GIMP Palette$/i.test(line) || /^(Name|Columns):/i.test(line)) continue;
    const m = line.match(/^(\d{1,3})\s+(\d{1,3})\s+(\d{1,3})\s+(.+)$/);
    if (!m) continue;
    const rgb = [Number(m[1]), Number(m[2]), Number(m[3])];
    if (rgb.some((v) => v > 255)) continue;
    const rest = m[4].trim();
    const lastSpace = rest.search(/\s\S+$/);
    const lastTok = lastSpace >= 0 ? rest.slice(lastSpace).trim() : "";
    let name, code;
    if (lastTok && /\d/.test(lastTok)) {
      name = rest.slice(0, lastSpace).trim();
      code = lastTok;
    } else {
      name = rest;
      code = "";
    }
    if (!name) { name = code; code = ""; }
    entries.push({ name, code, rgb });
  }
  return entries;
}

const brands = [];
for (const b of BRANDS) {
  const text = readFileSync(join(PALETTE_DIR, b.file), "utf8");
  const threads = parseGpl(text);
  if (threads.length < 50) {
    throw new Error(`${b.file}: parsed only ${threads.length} entries -- format change?`);
  }
  brands.push({ id: b.id, label: b.label, threads });
  console.log(`${b.label}: ${threads.length} colors`);
}

const header = `// threadBrands.js — GENERATED by tools/build-threads.mjs; do not edit by hand.
// Real manufacturer thread charts (name + catalog number + approximate RGB)
// for the ThreadPicker's brand mode and the Download step's thread summary.
// Source data: Ink/Stitch palette files (github.com/inkstitch/inkstitch,
// palettes/) — factual manufacturer color-chart data. Brand names are
// trademarks of their respective manufacturers, used only for identification.
// Every entry is { name, code, rgb: [r,g,b] }.
`;

const body = `export const THREAD_BRANDS = ${JSON.stringify(brands, null, 1)};\n`;
writeFileSync(OUT, header + body);
console.log(`Wrote ${OUT}`);
